version: "3.5"
services:
  cloud-discovery:
    image: lukkascost/cloud-discovery
    restart: always
    ports:
      - "8761:8761"
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 700M
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  api-gateway:
    image: lukkascost/api-gateway
    restart: always
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 700M
    environment:
      BROKER_URL: 192.168.1.19-artemis
      BROKER_PORT: 61616
      BROKER_USER: admin
      BROKER_PASSWORD: admin
      EUREKA_URI: http://cloud-discovery:8761/eureka
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    depends_on:
      - cloud-discovery

  attributes-module:
    image: lukkascost/data-analyze-attributes-module
    restart: always
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 700M
    environment:
      BROKER_URL: 192.168.1.19
      BROKER_PORT: 61616
      BROKER_USER: admin
      BROKER_PASSWORD: admin
      EUREKA_URI: http://cloud-discovery:8761/eureka
      DATASOURCE_JDBC: jdbc:postgresql://192.168.1.19:5432/data_analyze_db
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    depends_on:
      - cloud-discovery
  samples-module:
    image: lukkascost/data-analyze-samples-module
    restart: always
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 700M
    environment:
      BROKER_URL: 192.168.1.19
      BROKER_PORT: 61616
      BROKER_USER: admin
      BROKER_PASSWORD: admin
      EUREKA_URI: http://cloud-discovery:8761/eureka
      DATASOURCE_JDBC: jdbc:postgresql://192.168.1.19:5432/data_analyze_db
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    depends_on:
      - cloud-discovery
  dataset-module:
    image: lukkascost/data-analyze-dataset-module
    restart: always
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 700M
    environment:
      BROKER_URL: 192.168.1.19
      BROKER_PORT: 61616
      BROKER_USER: admin
      BROKER_PASSWORD: admin
      EUREKA_URI: http://cloud-discovery:8761/eureka
      DATASOURCE_JDBC: jdbc:postgresql://192.168.1.19:5432/data_analyze_db
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    depends_on:
      - cloud-discovery

  experiment-module:
    image: lukkascost/data-analyze-experiments-module
    restart: always
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 700M
    environment:
      BROKER_URL: 192.168.1.19
      BROKER_PORT: 61616
      BROKER_USER: admin
      BROKER_PASSWORD: admin
      EUREKA_URI: http://cloud-discovery:8761/eureka
      DATASOURCE_JDBC: jdbc:postgresql://192.168.1.19:5432/data_analyze_db
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    depends_on:
      - cloud-discovery
  round-module:
    image: lukkascost/data-analyze-round-module
    restart: always
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 700M
    environment:
      BROKER_URL: 192.168.1.19
      BROKER_PORT: 61616
      BROKER_USER: admin
      BROKER_PASSWORD: admin
      EUREKA_URI: http://cloud-discovery:8761/eureka
      DATASOURCE_JDBC: jdbc:postgresql://192.168.1.19:5432/data_analyze_db
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    depends_on:
      - cloud-discovery
  executions-module:
    image: lukkascost/data-analyze-execution-module
    restart: always
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 700M
    environment:
      BROKER_URL: 192.168.1.19
      BROKER_PORT: 61616
      BROKER_USER: admin
      BROKER_PASSWORD: admin
      EUREKA_URI: http://cloud-discovery:8761/eureka
      DATASOURCE_JDBC: jdbc:postgresql://192.168.1.19:5432/data_analyze_db
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
      REDIS_HOST: 192.168.1.19
      REDIS_PORT: 6379
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    depends_on:
      - cloud-discovery