name: build rounds image

on:
  push:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the commons image
        run: |
          docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag lukkascost/data-analyze-commons:latest commons.module/
      - name: build the rounds image
        run: |
          docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag lukkascost/data-analyze-round-module:latest rounds.module/
      
